version: "2.0"

services:
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000